backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

site_url: https://shinheechin.netlify.app
display_url: https://shinheechin.netlify.app
logo_url: https://shinheechin.netlify.app/static/img/logo.svg

collections:
  # Work projects
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    label_singular: "Project"
    folder: "projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "imgSrc", widget: "image" }
          - { label: "Caption", name: "imgDesc", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  # News posts
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    label_singular: "Post"
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
  # Exhibitions Shows
  - name: "exhibitions" # Used in routes, e.g., /admin/collections/blog
    label: "Exhibitions" # Used in the UI
    label_singular: "Show"
    folder: "shows" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Thumbnail", name: "thumbnail", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  # Pages e.g. About
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "pages"
    create: true # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
  # Home Page
  - name: "home"
    label: "Home"
    files:
      - name: "home"
        label: "Home"
        file: "home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Permalink", name: "permalink", widget: "string" }
          - label: "Images"
            name: "images"
            widget: "list"
            fields:
              - { label: "Image", name: "imgSrc", widget: "image" }
              - { label: "Caption", name: "imgDesc", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }